


project_DIRECTORY := ~/Git/MQTT-Scheduler
include_DIRECTORY := ~/Git/MQTT-Scheduler/include
support_LIB := ~/Git/MQTT-Scheduler/lib/libMQTT.a

working_DIRECTORY := ~/Git/MQTT-Scheduler/tests/test-ipc
program_NAME := test-ipc
 
#  set directories
system_BINARIES := $(project_DIRECTORY)/bin
working_DIRECTORY := $(project_DIRECTORY)/$(PROJECT)

# program_INCLUDE_DIRS := $(project_DIRECTORY)/include
program_INCLUDE_DIRS := $(include_DIRECTORY)


include ~/Git/MQTT-Scheduler/mastermake/Makefile