


project_DIRECTORY := ~/Git/MQTT-Scheduler
system_BINARIES := ~/Git/MQTT-dev/bin
working_DIRECTORY := ~/Git/MQTT-Scheduler/tests/hellow
program_LIB := ~/Git/MQTT-Scheduler/lib/libMQTT.a
support_LIB := ~/Git/MQTT-dev/lib/libMQTT.a
program_NAME := test-hellow

include ~/Git/MQTT-dev/mastermake/Makefile