


project_DIRECTORY := ~/Git/MQTT-Scheduler
project_BINARIES := ~/Git/MQTT-dev/bin
program_INCLUDE_DIRS := ~/Git/MQTT-dev/include /media/sysuts/mariadb-connector-c-3.1.11-ubuntu-focal-amd64/include
program_DIRECTORY := ~/Git/MQTT-Scheduler/tests/hellow
project_LIB := ~/Git/MQTT-Scheduler/lib/libMQTT.a
support_LIB := ~/Git/MQTT-dev/lib/libMQTT.a
program_NAME := test-hellow


include ~/Git/MQTT-dev/mastermake/Makefile