


project_DIRECTORY := ~/Git/MQTT-Scheduler
working_DIRECTORY := ~/Git/MQTT-Scheduler/tests/hellow
program_LIB := ~/Git/MQTT-Scheduler/lib/libMQTT.a
program_NAME := test-hellow

include ~/Git/MQTT-Scheduler/mastermake/Makefile