
# export project_LIBRARY_DIRS := $(project_DIRECTORY)/lib /media/sysuts/mariadb-connector-c-3.1.11-ubuntu-focal-amd64/lib/mariadb


export project_DIRECTORY=~/Git/MQTT-dev
export project_INCLUDE_DIRS := $(project_DIRECTORY)/include /media/sysuts/mariadb-connector-c-3.1.11-ubuntu-focal-amd64/include/mariadb
export project_BINARIES := $(project_DIRECTORY)/bin
export project_LIB := MQTT
export project_LIBRARY_DIRS := /home/mam1/Git/MQTT-dev/lib/
program_DIRECTORY := ~/Git/MQTT-Scheduler/tests/lib
program_NAME := tlib

include $(project_DIRECTORY)/mastermake/Makefile