


project_DIRECTORY := ~/Git/MQTT-Scheduler
working_DIRECTORY := ~/Git/MQTT-Scheduler/tests/sql
program_LIB := ~/Git/MQTT-Scheduler/lib/libMQTT.a
program_NAME := test-test-sql

include ~/Git/MQTT-Scheduler/mastermake/Makefile