


export project_DIRECTORY=~/Git/MQTT-dev
project_INCLUDE_DIRS := $(project_DIRECTORY)/include /media/sysuts/mariadb-connector-c-3.1.11-ubuntu-focal-amd64/include/mariadb
project_BINARIES := $(project_DIRECTORY)/bin
project_LIB := ~/Git/MQTT-Scheduler/lib/libMQTT.a
project_LIBRARY_DIRS := $(project_DIRECTORY)/lib /media/sysuts/mariadb-connector-c-3.1.11-ubuntu-focal-amd64/lib/mariadb

program_DIRECTORY := ~/Git/MQTT-Scheduler/tests/sql
program_NAME := test-sql

include $(project_DIRECTORY)/mastermake/Makefile