
# export project_LIBRARY_DIRS := $(project_DIRECTORY)/lib /media/sysuts/mariadb-connector-c-3.1.11-ubuntu-focal-amd64/lib/mariadb


export project_DIRECTORY=~/Git/MQTT-dev
export project_INCLUDE_DIRS := $(project_DIRECTORY)/include /media/sysuts/mariadb-connector-c-3.1.11-debian-9-stretch-amd64/include/mariadb
export project_BINARIES := $(project_DIRECTORY)/bin
export project_LIB := MQTT mariadbclient
export project_LIBRARY_DIRS := /home/mam1/Git/MQTT-dev/lib /media/sysuts/mariadb-connector-c-3.1.11-debian-9-stretch-amd64/lib/mariadb

program_DIRECTORY := ~/Git/MQTT-dev/tests/sql
program_NAME := test-sql
include $(project_DIRECTORY)/mastermake/Makefile
