


project_DIRECTORY := ~/Git/MQTT-Scheduler
working_DIRECTORY := ~/Git/MQTT-Scheduler/tests/stack
program_LIB := ~/Git/MQTT-Scheduler/lib/libMQTT.a
program_NAME := test-stack

include ~/Git/MQTT-Scheduler/mastermake/Makefile