#!/bin/bash
#####################################
# 
#	 cp_daemon  status
#
#####################################

echo "checking for active processes"

plist=$(pidof /usr/local/sbin/cp_daemon)
# echo $plist
if [ "$plist" != "" ] 
	then
		hlist="there is an instance of cp_daemon active pid " 
		hlist=$hlist$plist
		echo $hlist
		echo -n "  should it be killed? {y}{n} > "
		read answr

		# echo $answr

		if [ "$answr" == "y" ] 
			then
				echo -n "killing process "
				echo $plist
				kill $plist
		fi
	else
		echo -n "  there are no instances of cp_daemon active should one be started? {y}{n} > "
		read answr
		if [ "$answr" == "y" ]
			then
				echo "starting daemon"
				cp_daemon > /home/mam1/Git/MQTT-dev/logs/cp_daemon.log &
		fi
fi
