#!/bin/bash
# MQTT-dev system status
echo -e \\033c		# clear the terminal screen
stty cooked			# switch to buffered iput
stty echo			# turn on terminal echo


echo -e "\n        MQTT-dev system status"
echo "****************************************"

echo -e "\nterminal io reinitialized\n"

plist=$(pidof ~/Git/MQTT-dev/bin/cp_daemon)

if [ "$plist" != "" ] 
	then
		echo -e "there is an instance of cp_daemon active\n" 
	
	else
		echo -e "there are no instances of cp_daemon active\n"		
fi

plist=$(pidof ~/Git/MQTT-dev/bin/conwatcher)

if [ "$plist" != "" ] 
	then
		echo -e "there is an instance of conwatcher active\n" 
	else
		echo -e "there are no instances of conwatcher active\n"	
fi


plist=$(pidof ~/Git/MQTT-dev/bin/toker)

if [ "$plist" != "" ] 
	then
		echo -e "there is an instance of toker active\n" 

	else
		echo -e "there are no instances of toker active\n"
fi


exit 0